-- INSERT INTO USER (USERNAME, PASSWORD) VALUES ('vivek', 'password1');
-- INSERT INTO USER (USERNAME, PASSWORD) VALUES ('vinay', 'password2');
-- 11 Rounds of Bcrypt

INSERT INTO USER (USERNAME, PASSWORD) VALUES ('vivek', '$2y$11$pM1MdNaQWEOKC0uVgWZHV.Shn1zELaZNjhuFOwhQIRL.94ShTxNyS');
INSERT INTO USER (USERNAME, PASSWORD) VALUES ('vinay', '$2y$11$hUOhzj.XooEaQQhAjL2cdeTZod4vVJgZ0QmEoN0Xny2ArlXPDhxG2');

INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('vivek', 'USER');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('vivek', 'ADMIN');
INSERT INTO AUTH_USER_GROUP (USERNAME, AUTH_GROUP) VALUES('vinay', 'USER');